### ISSUE TITLE
Codec error when converting movie lens dataset

### ISSUE THREAD

**Issue by guedes-joaofelipe** [RUCAIBox/RecSysDatasets#94]
I followed the instructions on Readme.md to download and convert the movie lens dataset but I got the following error: 

**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 2892: invalid continuation byte**

Just changed the _pd.read_csv_ method on file _convertion_tools/src/extended_dataset.py_ (line 52) to include an encoding argument and fix the problem.

**Comment by EliverQ** [comment]
Hi, @guedes-joaofelipe! Thank you for your issue, but we can't reproduce the problem here. So could you please check your dataset and your environment again?

**Comment by ZZZZZZZZeng** [comment]
I had the same problem.

**Comment by ZZZZZZZZeng** [comment]
@EliverQ I had the same problem，When I convert the yelp data set on windows。
--------------------------------------------------------
Traceback (most recent call last):
  File "run.py", line 40, in <module>
    datasets.convert_inter()
  File "D:\学业\研究生\数据集\数据集转换程序\RecSysDatasets-master\conversion_tools\src\extended_dataset.py", line 4581, in convert_inter
    for _ in fin:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 1909: illegal multibyte sequence
